version: "3"

services:
  deltalake:
    image: deltaio/delta-docker:latest_arm64
    platform: linux/arm64
    hostname: deltalake-quickstart
    container_name: deltalake-quickstart
    volumes:
      - ${PWD}:/opt/spark/work-dir/ch5
      - ${PWD}/../datasets:/opt/spark/work-dir/ch5
    ports:
      - 8888-8889:8888-8889
    restart: always
